// <auto-generated />
using Elo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Elo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EloDbContext))]
    [Migration("20260905120000_CdigitalProducao")]
    partial class CdigitalProducao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot compartilhado em EloDbContextModelSnapshot.
        }
    }
}
