// <auto-generated />
using System;
using Elo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EloDbContext))]
    partial class EloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elo.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnderecoIp")
                        .HasColumnType("text");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("auditoria_logs", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.FormularioClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AntimicrobianosAntesDescricao")
                        .HasColumnType("text");

                    b.Property<string>("AntimicrobianosDescricao")
                        .HasColumnType("text");

                    b.Property<string>("AntimicrobianosDiaColetaDescricao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsistenciaFezes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DesorientacaoConfusao")
                        .HasColumnType("integer");

                    b.Property<int>("Diarreia")
                        .HasColumnType("integer");

                    b.Property<int?>("DiasInicioSintomas")
                        .HasColumnType("integer");

                    b.Property<int>("DorAbdominal")
                        .HasColumnType("integer");

                    b.Property<int>("DrogasVasoativas")
                        .HasColumnType("integer");

                    b.Property<string>("DuracaoFebre")
                        .HasColumnType("text");

                    b.Property<int?>("EpisodiosDiarreia24h")
                        .HasColumnType("integer");

                    b.Property<int>("Febre")
                        .HasColumnType("integer");

                    b.Property<int>("FezIra")
                        .HasColumnType("integer");

                    b.Property<string>("IbpDescricao")
                        .HasColumnType("text");

                    b.Property<int>("IleoParalitico")
                        .HasColumnType("integer");

                    b.Property<int>("InternouUtiDurante")
                        .HasColumnType("integer");

                    b.Property<int>("Leucocitose")
                        .HasColumnType("integer");

                    b.Property<int>("Leucopenia")
                        .HasColumnType("integer");

                    b.Property<int>("Megacolon")
                        .HasColumnType("integer");

                    b.Property<int>("NutricaoParenteral")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacoesClinicas")
                        .HasColumnType("text");

                    b.Property<int>("Peritonite")
                        .HasColumnType("integer");

                    b.Property<string>("SintomasAssociados")
                        .HasColumnType("text");

                    b.Property<Guid>("SolicitacaoExameId")
                        .HasColumnType("uuid");

                    b.Property<int>("SondaNasogastrica")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemperaturaMaxima")
                        .HasColumnType("numeric");

                    b.Property<int>("UsoAntimicrobiano30d")
                        .HasColumnType("integer");

                    b.Property<int>("UsoAntimicrobianoAntesColeta")
                        .HasColumnType("integer");

                    b.Property<int>("UsoAntimicrobianoDiaColeta")
                        .HasColumnType("integer");

                    b.Property<int>("UsoIbp")
                        .HasColumnType("integer");

                    b.Property<int>("UsoIbpAntesDiarreia")
                        .HasColumnType("integer");

                    b.Property<int>("UsoIbpDuranteDiarreia")
                        .HasColumnType("integer");

                    b.Property<int>("VentilacaoMecanica")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoExameId")
                        .IsUnique();

                    b.ToTable("formularios_clinicos", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.Internacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInternacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataObito")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmUti")
                        .HasColumnType("integer");

                    b.Property<string>("Enfermaria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImunossupressoresDescricao")
                        .HasColumnType("text");

                    b.Property<int>("InternouComDiarreia")
                        .HasColumnType("integer");

                    b.Property<bool>("IsolamentoAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Leito")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Leucocitose")
                        .HasColumnType("integer");

                    b.Property<int>("Leucopenia")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoInternacao")
                        .HasColumnType("text");

                    b.Property<int>("Obito")
                        .HasColumnType("integer");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParaTcth")
                        .HasColumnType("integer");

                    b.Property<int>("ParaTos")
                        .HasColumnType("integer");

                    b.Property<int>("Sepse")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCirurgia")
                        .HasColumnType("integer");

                    b.Property<int>("UsoImunossupressoresAtual")
                        .HasColumnType("integer");

                    b.Property<int>("UsoImunossupressoresDurante")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("internacoes", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PerfilDestino")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SolicitacaoExameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UsuarioDestinoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("SolicitacaoExameId");

                    b.HasIndex("UsuarioDestinoId");

                    b.HasIndex("Lida", "PerfilDestino");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CdiffFamiliaAmbiente")
                        .HasColumnType("integer");

                    b.Property<string>("CovidAnosPositivos")
                        .HasColumnType("text");

                    b.Property<int?>("CovidDiasInternacao")
                        .HasColumnType("integer");

                    b.Property<int?>("CovidDiasIntubado")
                        .HasColumnType("integer");

                    b.Property<int>("CovidInternado")
                        .HasColumnType("integer");

                    b.Property<int>("CovidIntubado")
                        .HasColumnType("integer");

                    b.Property<int>("CovidOxigenioOuTratamentos")
                        .HasColumnType("integer");

                    b.Property<string>("CovidQuandoIntubacao")
                        .HasColumnType("text");

                    b.Property<string>("CovidSintomasDescricao")
                        .HasColumnType("text");

                    b.Property<int>("CovidTeveSintomas")
                        .HasColumnType("integer");

                    b.Property<string>("CovidTratamentosDescricao")
                        .HasColumnType("text");

                    b.Property<int>("CovidUtiDuranteIntubacao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("DiarreiaAssociadaAtbPassado")
                        .HasColumnType("integer");

                    b.Property<int>("HistoricoCdiff")
                        .HasColumnType("integer");

                    b.Property<int>("HistoricoCovid")
                        .HasColumnType("integer");

                    b.Property<int>("HistoricoDiarreiaPrevia")
                        .HasColumnType("integer");

                    b.Property<int>("HistoricoQuimioterapia")
                        .HasColumnType("integer");

                    b.Property<int>("HistoricoTransplante")
                        .HasColumnType("integer");

                    b.Property<int>("InternadoPorDiarreia")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NumeroProntuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProblemasSaudeAdjacentes")
                        .HasColumnType("text");

                    b.Property<string>("ProblemasSaudeOutros")
                        .HasColumnType("text");

                    b.Property<int>("ProcurouAtendimentoPorDiarreia")
                        .HasColumnType("integer");

                    b.Property<string>("QuandoInternadoPorDiarreia")
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NumeroProntuario")
                        .IsUnique();

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.ResultadoLaboratorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlertaPositivoEnviado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CepaIdentificada")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssinaturaBase64")
                        .HasColumnType("text");

                    b.Property<string>("AssinadoPorNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("AssinadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Cultura")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAlertaEnviado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataLiberacaoIsolamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataResultado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LiberacaoIsolamentoEnviada")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("LaudoAnexoBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("LaudoAnexoContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LaudoAnexoNome")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTime?>("LaudoGeradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObservacoesLaboratorio")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SolicitacaoExameId")
                        .HasColumnType("uuid");

                    b.Property<int>("TesteRapido")
                        .HasColumnType("integer");

                    b.Property<int>("ToxinaA")
                        .HasColumnType("integer");

                    b.Property<int>("ToxinaB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SolicitacaoExameId")
                        .IsUnique();

                    b.ToTable("resultados_laboratoriais", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.SolicitacaoExame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CarimboDataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAvaliacaoAmostra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataColeta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRecebimentoLaboratorio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdAmostraUnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("InternacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("QualidadeAmostra")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdAmostraUnico")
                        .IsUnique();

                    b.HasIndex("InternacaoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("solicitacoes_exame", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.TratamentoCdiff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicioTratamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRecidiva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dose")
                        .HasColumnType("text");

                    b.Property<int?>("DuracaoDias")
                        .HasColumnType("integer");

                    b.Property<int>("IniciouTratamento")
                        .HasColumnType("integer");

                    b.Property<string>("Medicacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ObservacoesTratamento")
                        .HasColumnType("text");

                    b.Property<int>("Recidiva")
                        .HasColumnType("integer");

                    b.Property<int>("RespostaDia7")
                        .HasColumnType("integer");

                    b.Property<int>("RespostaFinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("SolicitacaoExameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoExameId")
                        .IsUnique();

                    b.ToTable("tratamentos_cdiff", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Setor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.SolicitacaoAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PerfilSolicitado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("RevisadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevisadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Setor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UsuarioCriadoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("RevisadoPorId");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioCriadoId");

                    b.ToTable("solicitacoes_acesso", (string)null);
                });

            modelBuilder.Entity("Elo.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("Elo.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Elo.Domain.Entities.FormularioClinico", b =>
                {
                    b.HasOne("Elo.Domain.Entities.SolicitacaoExame", "SolicitacaoExame")
                        .WithOne("FormularioClinico")
                        .HasForeignKey("Elo.Domain.Entities.FormularioClinico", "SolicitacaoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoExame");
                });

            modelBuilder.Entity("Elo.Domain.Entities.Internacao", b =>
                {
                    b.HasOne("Elo.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Internacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Elo.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("Elo.Domain.Entities.SolicitacaoExame", "SolicitacaoExame")
                        .WithMany()
                        .HasForeignKey("SolicitacaoExameId");

                    b.HasOne("Elo.Domain.Entities.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoId");

                    b.Navigation("SolicitacaoExame");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("Elo.Domain.Entities.ResultadoLaboratorial", b =>
                {
                    b.HasOne("Elo.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.HasOne("Elo.Domain.Entities.SolicitacaoExame", "SolicitacaoExame")
                        .WithOne("ResultadoLaboratorial")
                        .HasForeignKey("Elo.Domain.Entities.ResultadoLaboratorial", "SolicitacaoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("SolicitacaoExame");
                });

            modelBuilder.Entity("Elo.Domain.Entities.SolicitacaoExame", b =>
                {
                    b.HasOne("Elo.Domain.Entities.Internacao", "Internacao")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("InternacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elo.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Elo.Domain.Entities.Usuario", "Solicitante")
                        .WithMany("SolicitacoesRealizadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Internacao");

                    b.Navigation("Paciente");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Elo.Domain.Entities.SolicitacaoAcesso", b =>
                {
                    b.HasOne("Elo.Domain.Entities.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Elo.Domain.Entities.Usuario", "UsuarioCriado")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RevisadoPor");

                    b.Navigation("UsuarioCriado");
                });

            modelBuilder.Entity("Elo.Domain.Entities.TratamentoCdiff", b =>
                {
                    b.HasOne("Elo.Domain.Entities.SolicitacaoExame", "SolicitacaoExame")
                        .WithOne("TratamentoCdiff")
                        .HasForeignKey("Elo.Domain.Entities.TratamentoCdiff", "SolicitacaoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoExame");
                });

            modelBuilder.Entity("Elo.Domain.Entities.Internacao", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("Elo.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Internacoes");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("Elo.Domain.Entities.SolicitacaoExame", b =>
                {
                    b.Navigation("FormularioClinico");

                    b.Navigation("ResultadoLaboratorial");

                    b.Navigation("TratamentoCdiff");
                });

            modelBuilder.Entity("Elo.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("SolicitacoesRealizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
